### ISSUE TITLE
Error on Thanksgiving.java

### ISSUE THREAD

**Issue by ian-smithh** [ian-smithh/CS11A_Final#7]
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at Thanksgiving.Adjective(Thanksgiving.java:44)
        at Thanksgiving.main(Thanksgiving.java:6)

**Comment by ian-smithh** [comment]
Resolved with 3105f3de5ba81d60a012b6f6b6183c3f0e8aec96
